<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="NRMI-55" name="Default test" tests="126" failures="54" timestamp="28 Jul 2020 08:41:01 GMT" time="43.944" errors="0">
  <testcase name="createOrUpdateLoanProductTest" time="2.902" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.364" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.329" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.303" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.267" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.296" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.284" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.319" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.33" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.294" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.329" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.314" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.269" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.271" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.418" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.367" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.269" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.328" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.335" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.278" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.386" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.271" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.307" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.245" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.261" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.413" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.243" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.277" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.285" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.265" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.368" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.351" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.293" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.257" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.294" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.267" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.31" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.322" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.308" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.261" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.32" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.302" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.302" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.323" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.376" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.278" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.317" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.264" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.328" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.267" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.266" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.534" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.275" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.278" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.291" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.305" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.312" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.272" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.275" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.259" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.31" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.253" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.252" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.27" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.275" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.315" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.25" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.25" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.288" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.273" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.259" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.294" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.287" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.255" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.266" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.267" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.3" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.284" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.306" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.298" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.4" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.321" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.334" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.345" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.267" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.295" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.258" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.272" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.273" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.355" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.282" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.278" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.282" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.28" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.265" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.256" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.44" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.29" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.279" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.28" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.265" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.292" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.301" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.315" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.311" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.303" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.278" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.279" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.264" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.272" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.277" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.244" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.253" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.245" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.334" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.334" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.407" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.298" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.327" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.326" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.273" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.314" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.31" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.285" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.298" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.278" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <failure type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOrUpdateLoanProductTest -->
</testsuite> <!-- Default test -->
