<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-L7AGLPD" name="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest" tests="118" failures="0" timestamp="25 Aug 2020 09:39:57 GMT" time="77.788" errors="68">
  <testcase name="createOrUpdateLoanProductTest" time="0.540" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.672" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.610" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.583" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.584" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.589" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.718" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.670" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.551" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.529" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.579" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.547" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.651" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.558" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.987" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.555" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.601" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.607" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.576" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.708" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.558" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.575" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.746" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.543" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.591" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.545" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.585" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.604" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.586" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.659" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.624" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.550" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.579" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.639" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.758" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.535" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.631" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.594" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.554" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.588" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.575" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.594" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.585" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.574" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.987" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.600" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.539" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.597" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.590" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.593" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.592" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.581" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.792" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.609" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.642" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.549" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="1.857" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.548" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.585" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.538" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.573" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.811" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.671" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.575" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.610" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.569" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.624" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.555" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.836" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.751" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.558" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.593" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.854" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.607" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.558" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.575" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.575" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.582" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.599" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.635" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.592" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.582" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.777" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.591" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.605" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.579" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.588" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.594" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.571" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="2.001" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.595" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.620" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.556" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.538" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.603" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.570" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.543" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.585" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.581" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.547" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.548" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.599" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.603" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.594" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.671" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.553" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.643" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.704" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.584" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.589" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.649" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.601" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.592" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.555" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="3.649" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.613" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
  <testcase name="createOrUpdateLoanProductTest" time="0.529" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest"/>
  <testcase name="createOrUpdateLoanProductTest" time="0.597" classname="in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest.createOrUpdateLoanProductTest(CreateOrUpdateLoanProductTest.java:50)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- createOrUpdateLoanProductTest -->
</testsuite> <!-- in.novopay.cbs.apis.createorupdateloanproduct.CreateOrUpdateLoanProductTest -->
